### PR TITLE
Guided setup Workflow

### PR DESCRIPTION
**Pull request by Huongg**
The flow I have in mind for GuidedSetup is:
- Form with 5 different tabs/pages
- Whenever user clicks any button (eg: next, previous, preview, job, etc), it should dispatch the data right away. I haven't managed to find the right actions to do this btw.
- Thinking of this structure to store values from the form. What do you think? Is it something that similar with what we have in the BE/DB? Also locations can be an object rather than a string btw, wasn't sure what the data looks like

```
const defaultValues = {
  caller: {
    name: "",
    phone: "",
    email: "",
  },
  pickUpLocation: "",
  sender: {
    name: "",
    phone: "",
    email: "",
  },
  dropOffLocation: "",
  priority: "",
  items: {
    sample: 0,
    covidSample: 0,
    milk: 0,
    documents: 0,
    equipment: 0,
  },
}
```

With our discussion yesterday, I looked at ways to pass data from `TaskDialogCompact` to `GuidedSetup` but it doesn't seem right to me. As they should be 2 separate components and should not linked to each other? As in TaskDialogCompact renders when users click on the card itself, and GuidedSetup renders when users click create new

What do you think?

### CODE REVIEW

**Comment by Huongg** [comment]
hey, @duckbytes  I haven't managed to get and update the data yet, thought I would make a WIP PR anyway so we can discuss further.

**Comment by duckbytes** [comment]
Thanks Huong.

It looks good to me so far.

The data structure is something like this:

```requester_contact: {
    name: string,
    telephone_number: string,
    email_address: string,
},
pickup_location_uuid: UUID,
dropoff_location_uuid: UUID,
pickup_location: returns from the server a location object with the fields below,
dropoff_location: same as pickup,
deliverables: [UUID],
priority_id: int,
priority: string, - only on return from the server, set the priority on the backend by setting priority_id
```
Locations have the format:
```
  uuid: string,
  name: string,
  contact: {name: string, telephone_number: string, email_address: string},
  address:
      ward: string,
      line1: string,
      line2: string,
      town: string,
      county: string,
      country: string,
      postcode: string,
      what3words: string,
 protected: bool, (protected means it can't be edited),
 listed: bool (listed means it's in the directory, usually listed and protected are both set to True or both to False)
```

To set the pickup and dropoff locations you either set pickup/dropoff_location_uuid to an existing UUID for a Location in the directory or post a new Location to the server if it is a custom address and link the newly created Location UUID to the task.

src/scenes/Task/components/PickUpDetails.js is an example (the location prop is task.pickup_location, like it's used in TaskOverview.js).

it might be helpful to look at the schemas file on the backend here - https://github.com/platelet-app/platelet-api/blob/master/app/schemas.py

Each class represents an object on the backend and `class Meta: fields=()` describes which fields are available

Yeah, separating it from TaskDialogCompact seems like a good idea. Maybe it should become its own new scene? Like put everything src/scenes/GuidedTaskSetup ? Then feel free to just import components from src/scenes/Task/components for now until we can think more about the structure.

A couple of other ideas:

- could make the dialog either a fixed height or fullscreen so that the buttons stay in a fixed place
- have a look at src/components/TextFields.js, there are controlled and uncontrolled text fields there that have telephone validation if you pass in the tel prop.

I wonder if the best way to deal with sending data to the server would be to generate a task UUID client side and queue up redux dispatch actions with it, saving them into a list with useRef. The DeliverableGridSelect component and CommentsSection will need to do something similar as they return a notfound error if the parent doesn't exist.

In the meantime though it might be quicker to create the task when clicking the create new button and then we can look at implementing something like a queue after Tuesday (or whatever is best for a graphql workflow). You could generate the UUID in const emptyTask of TasksGrid if it's quicker to pass the UUID to the guided setup that way instead of getting it after the request has succeeded.

If we're going to include the comments section sidebar during the guided setup then feel free to move src/scenes/Task/components/CommentsSideBar.js into src/components so it can be used anywhere (makes more sense when I think about it!).

**Comment by Huongg** [comment]
hey @duckbytes ,

everything seems working fine but I couldn't get to render the `TaskOverview` when lets say user clicks on `Skip to overview`. 

I passed these props to the component 

```
{showTaskOverview && <TaskOverview task={task} taskUUID={task.uuid} />}
```

but when it throws error saying that 

```
The prop taskUUID is marked as required in TaskAssignees, but its value is null.
```

I can log the value fine, it returns the string

**Comment by duckbytes** [comment]
hey @Huongg 

I think the best way would be to redirect to the URL for the new task.

You could try doing something like this in your parent component:
```
if (taskGuidedSetupComplete)
    return <Redirect push to={`/task/${encodeUUID(theNewTaskUUID)}`}/>
```
I haven't tried it out myself but there is some documentation here https://reactrouter.com/web/api/Redirect

**Comment by Huongg** [comment]
@duckbytes ah i see. I used `history.push` and it's working fine

**Comment by duckbytes** [comment]
Ah nice, it looks great.

Line 164 in GuidedSetup.js is dispatching to the dropoff address but should be setTaskPickupDestinationRequest.

I pushed up some more changes to locations_details_contacts so that the contact details only show on the LocationDetailsAndSelector if a prop is set. I testing merging it into your branch and it seems to work well without interfering with your form. Feel free to merge it into this branch if you'd like.

**Comment by Huongg** [comment]
@duckbytes thanks for spotting it. Updated it now, also moved `GuidedSetup` to `scenes` now. 

maybe if its working fine when you merge testing it, you can merge mine to yours, and double-check one more time. If all looks good maybe we can merge to master?

as i expect we need to give them a live version to play around with?

also what time is a call today btw?

**Comment by duckbytes** [comment]
@Huongg I've merged the branch into this one and pushed it up.

If you're happy with everything for the demonstration we can merge to master and get Jeremy's and Tim's feedback before tonight.

The call is at 7pm. Do you have a link for it?

**Comment by Huongg** [comment]
@duckbytes updated one small thing but it looks good to me. Just merged it now.

Do you think how long it takes to deploy everything? Just so we know when its ready for Jeremy and Tim to check out?

**Comment by duckbytes** [comment]
@Huongg Great, thanks. The deployment is updated and working now.

**Pull request merged**
